# Generated by Django 4.2.6 on 2023-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_alter_customuser_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pathology_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="surname",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
