# Generated by Django 4.2.6 on 2024-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_gamesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="number_objects",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="number_objects",
            field=models.IntegerField(default=5),
        ),
    ]
