# Generated by Django 4.2.6 on 2024-05-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0007_rename_gamesession_gamesession_findobjects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="remote_difficulty",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="gamesession_remotecontrol",
            name="remote_difficulty",
            field=models.IntegerField(default=1),
        ),
    ]
